// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtWLPFOTCzEELXnNK25yNykDWCiisbKfg',
    appId: '1:284961146938:android:6b1ff01b7a54506b100d03',
    messagingSenderId: '284961146938',
    projectId: 'soloship-57b40',
    storageBucket: 'soloship-57b40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_fD8m8MprVPpoaa1NjusLByePtZVGCnY',
    appId: '1:284961146938:ios:cbd718eec5e9647d100d03',
    messagingSenderId: '284961146938',
    projectId: 'soloship-57b40',
    storageBucket: 'soloship-57b40.firebasestorage.app',
    iosClientId: '284961146938-9tpd04u6i2lnflata0lt720e7kkt9dp8.apps.googleusercontent.com',
    iosBundleId: 'com.soloship.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxiYSqTexNeoj2rMRvGYtRzm6oaBxFeSc',
    appId: '1:284961146938:web:984c23303ca1ccc6100d03',
    messagingSenderId: '284961146938',
    projectId: 'soloship-57b40',
    authDomain: 'soloship-57b40.firebaseapp.com',
    storageBucket: 'soloship-57b40.firebasestorage.app',
    measurementId: 'G-918CJC6R8B',
  );

}